// Generated by CoffeeScript 1.8.0
(function() {
  define(['jquery', 'angular', 'angularCheckboxSet'], function($, angular) {
    var app;
    app = angular.module('mainModule', ['luxiyalu.checkboxSet']);
    return app.controller('appCtrl', function($scope, checkboxHooks) {
      $scope.grandParent = {
        identity: 'gp'
      };
      $scope.parents = [
        {
          identity: 'p1'
        }, {
          identity: 'p2'
        }
      ];
      $scope.childrenA = [
        {
          identity: 'ca1'
        }, {
          identity: 'ca2'
        }, {
          identity: 'ca3'
        }
      ];
      return $scope.childrenB = [
        {
          identity: 'cb1'
        }, {
          identity: 'cb2'
        }
      ];
    });
  });

}).call(this);
